services:
  postgres:
    container_name: opensociocracy-pg
    hostname: "postgres"
    command: ["postgres", "-c", "log_statement=all"]
    image: "postgres:14"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "5432:5432"
    restart: no
    env_file: .env
    networks:
      - opensociocracy-net
    volumes:
      - "./docker-postgres/sql:/sql"
      - opensociocracy-pg:/var/lib/postgres/data
      - ./docker-postgres:/docker-entrypoint-initdb.d/

  redis:
    image: redis:7.0.7
    container_name: opensociocracy-redis
    restart: no
    ports:
      - "6379:6379"
    networks:
      - opensociocracy-net
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - opensociocracy-redis:/data

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:4.6
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3567:3567
    container_name: opensociocracy-supertokens
    env_file: ".env"
    environment: 
      - POSTGRESQL_TABLE_SCHEMA=supertokens
    networks:
      - opensociocracy-net
    restart: no
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/0.0.0.0/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 0.0.0.0:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  smtp4dev:
    container_name: opensociocracy-smtp4dev
    image: rnwood/smtp4dev:v3
    restart: no
    env_file: .env
    networks:
      - opensociocracy-net
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
      - opensociocracy-smtp4dev:/smtp4dev

  api:
    container_name: opensociocracy-api
    image: opensociocracy/api
    restart: no
    build: ./api
    command: ["npm", "run", "start:debug"]
    # command: ["npm", "run", "dev:debug"]
    ports:
      - "3000:3000"
    env_file: ".env"
    networks:
      - opensociocracy-net
    volumes:
      - "./api/plugins:/usr/src/app/plugins"
      - "./api/routes:/usr/src/app/routes"
      - "./api/app.js:/usr/src/app/app.js"
      - "./api/server.js:/usr/src/app/server.js"


volumes:
  opensociocracy-smtp4dev: {}
  opensociocracy-pg: {}
  opensociocracy-redis: {}

networks:
  opensociocracy-net:
    external: false
    driver: bridge
